name: Local Docker Build Validation

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual trigger

permissions:
  id-token: write
  contents: read

jobs:
  docker-local-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          #client-secret: ${{ secrets.GITHUB_DEPLOYMENT_SP_CLIENT_SECRET }}

      - name: Build Docker image locally
        run: |
          docker build -t fakerestapi:local .
      
      - name: Run container for smoke test
        run: |
          docker run -d -p 8000:8000 --name api-test fakerestapi:local
          sleep 5
          curl -f http://localhost:8000//api/v1/Books || (echo "‚ùå Application failed to run in Docker!" && exit 1)


      - name: Cleanup container
        run: |
          docker stop api-test
          docker rm api-test
