name: Local Docker Build Validation

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual trigger

permissions:
  id-token: write
  contents: read

env:
  # The login server name for your Azure Container Registry (e.g., myregistry.azurecr.io)
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  # The name of the image repository inside ACR (e.g., 'myapp/api')
  IMAGE_NAME: flaskapp
  # Automatically generate a tag using the short SHA of the commit
  IMAGE_TAG: ${{ github.sha }}

jobs:
  docker-local-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          #client-secret: ${{ secrets.GITHUB_DEPLOYMENT_SP_CLIENT_SECRET }}

      - name: Build Docker image locally
        run: |
          docker build -t fakerestapi:local .
      
      - name: Run container for smoke test
        run: |
          docker run -d -p 8000:8000 --name api-test fakerestapi:local
          sleep 5
          curl -f http://localhost:8000//api/v1/Books || (echo "‚ùå Application failed to run in Docker!" && exit 1)

      # Build and Push Image to ACR
      - name: Build and Push to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: |
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Verify pushed images
        run: |
          az acr repository list --name ${{ env.ACR_NAME }} --output table
          
      - name: Cleanup container
        run: |
          docker stop api-test
          docker rm api-test
